@ECHO OFF
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_Character.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_Chat.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_Defins.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_Item.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_PacketCommand.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\_Reward.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Account.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Agent.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\CharacterClass.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Common.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Customize.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\DediServer.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Friend.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\GatheringHall.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Gm.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\InGame.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Inventory.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\IronMace.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Karma.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Lobby.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\MarketPlace.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Merchant.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Operate.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Party.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Ranking.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Shop.proto
protoc --proto_path=%cd%\protos --python_out=%cd%\pb2 %cd%\protos\Trade.proto
PAUSE