# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Customize.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'Customize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43ustomize.proto\x12\tDC.Packet\"k\n\x14SCUSTOMIZE_BASE_INFO\x12\x15\n\rcustomizeType\x18\x01 \x01(\r\x12\x13\n\x0b\x63ustomizeId\x18\x02 \x01(\t\x12\x0f\n\x07isEquip\x18\x03 \x01(\r\x12\x16\n\x0e\x65quipSlotIndex\x18\x04 \x01(\x05\"\x19\n\x17SC2S_CUSTOMIZE_INFO_REQ\"[\n\x17SS2C_CUSTOMIZE_INFO_RES\x12\x10\n\x08loopFlag\x18\x01 \x01(\r\x12.\n\x05infos\x18\x02 \x03(\x0b\x32\x1f.DC.Packet.SCUSTOMIZE_BASE_INFO\"^\n\x18SC2S_CUSTOMIZE_MOUNT_REQ\x12\x15\n\rcustomizeType\x18\x01 \x01(\r\x12\x13\n\x0b\x63ustomizeId\x18\x02 \x01(\t\x12\x16\n\x0e\x65quipSlotIndex\x18\x03 \x01(\r\"q\n\x18SS2C_CUSTOMIZE_MOUNT_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x15\n\rcustomizeType\x18\x02 \x01(\r\x12.\n\x05infos\x18\x03 \x03(\x0b\x32\x1f.DC.Packet.SCUSTOMIZE_BASE_INFO\"H\n\x1aSC2S_CUSTOMIZE_UNMOUNT_REQ\x12\x15\n\rcustomizeType\x18\x01 \x01(\r\x12\x13\n\x0b\x63ustomizeId\x18\x02 \x01(\t\"s\n\x1aSS2C_CUSTOMIZE_UNMOUNT_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x15\n\rcustomizeType\x18\x02 \x01(\r\x12.\n\x05infos\x18\x03 \x03(\x0b\x32\x1f.DC.Packet.SCUSTOMIZE_BASE_INFO\"3\n!SC2S_CUSTOMIZE_NEW_ITEM_CHECK_REQ\x12\x0e\n\x06itemId\x18\x01 \x01(\t\"#\n!SS2C_CUSTOMIZE_NEW_ITEM_CHECK_RES\"#\n!SS2C_CUSTOMIZE_NEW_ITEM_ALERT_NOTB$\n\x15\x63om.packets.customizeB\tcustomizeP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Customize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.packets.customizeB\tcustomizeP\000'
  _globals['_SCUSTOMIZE_BASE_INFO']._serialized_start=30
  _globals['_SCUSTOMIZE_BASE_INFO']._serialized_end=137
  _globals['_SC2S_CUSTOMIZE_INFO_REQ']._serialized_start=139
  _globals['_SC2S_CUSTOMIZE_INFO_REQ']._serialized_end=164
  _globals['_SS2C_CUSTOMIZE_INFO_RES']._serialized_start=166
  _globals['_SS2C_CUSTOMIZE_INFO_RES']._serialized_end=257
  _globals['_SC2S_CUSTOMIZE_MOUNT_REQ']._serialized_start=259
  _globals['_SC2S_CUSTOMIZE_MOUNT_REQ']._serialized_end=353
  _globals['_SS2C_CUSTOMIZE_MOUNT_RES']._serialized_start=355
  _globals['_SS2C_CUSTOMIZE_MOUNT_RES']._serialized_end=468
  _globals['_SC2S_CUSTOMIZE_UNMOUNT_REQ']._serialized_start=470
  _globals['_SC2S_CUSTOMIZE_UNMOUNT_REQ']._serialized_end=542
  _globals['_SS2C_CUSTOMIZE_UNMOUNT_RES']._serialized_start=544
  _globals['_SS2C_CUSTOMIZE_UNMOUNT_RES']._serialized_end=659
  _globals['_SC2S_CUSTOMIZE_NEW_ITEM_CHECK_REQ']._serialized_start=661
  _globals['_SC2S_CUSTOMIZE_NEW_ITEM_CHECK_REQ']._serialized_end=712
  _globals['_SS2C_CUSTOMIZE_NEW_ITEM_CHECK_RES']._serialized_start=714
  _globals['_SS2C_CUSTOMIZE_NEW_ITEM_CHECK_RES']._serialized_end=749
  _globals['_SS2C_CUSTOMIZE_NEW_ITEM_ALERT_NOT']._serialized_start=751
  _globals['_SS2C_CUSTOMIZE_NEW_ITEM_ALERT_NOT']._serialized_end=786
# @@protoc_insertion_point(module_scope)
