# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Gm.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'Gm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08Gm.proto\x12\tDC.Packet\"\x1e\n\x1cSC2S_GM_PARTY_ALL_RANDOM_REQ\"\x1e\n\x1cSS2C_GM_PARTY_ALL_RANDOM_RESB\x16\n\x0e\x63om.packets.gmB\x02gmP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Gm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.packets.gmB\002gmP\000'
  _globals['_SC2S_GM_PARTY_ALL_RANDOM_REQ']._serialized_start=23
  _globals['_SC2S_GM_PARTY_ALL_RANDOM_REQ']._serialized_end=53
  _globals['_SS2C_GM_PARTY_ALL_RANDOM_RES']._serialized_start=55
  _globals['_SS2C_GM_PARTY_ALL_RANDOM_RES']._serialized_end=85
# @@protoc_insertion_point(module_scope)
